Drop Python 2.7 CI on macOS.
It seems that the 2.7 binary used by the setup-python action on GitHub
no longer provides 2.7.. this may become a problem for our other
platforms where python 2 is still supported.

```
Run actions/setup-python@v1
Error: Version 2.7 with arch x64 not found
```